defaultContentLanguage = 'zh-cn'
languageCode = 'zh-CN'
baseURL = 'https://blog.gjcloak.top/'
title = '公爵书房'
theme = 'FixIt'
enableRobotsTXT = true
enableEmoji = true
summaryLength = 70
hasCJKLanguage = true
[permalinks]
  [permalinks.page]
    posts = '/:year/:month:day/:slug/'
[params]
  version = "v0.4.0-alpha.2"
  description = "这有关于P社相关的攻略教程，也有文章翻译和分享。相信你可以在这里找到对你有用的知识和教程"
  keywords = ["Hugo", "FixIt", "IT", "笔记", "博客"]
  [params.author]
    name = "公爵"
    email = "763771418@qq.com"
    link = "https://blog.gjcloak.top"
    avatar = "https://q.qlogo.cn/headimg_dl?dst_uin=763771418&spec=640"
  [params.breadcrumb]
    enable = true
    sticky = true
    showHome = true
    separator = "/"
    capitalize = false
  [params.navigation]
    inSection = true
    reverse = true
  [params.footer]
    enable = true
    copyright = true
    author = true
    since = "2022"
    gov = "闽公网安备35020502000606号"
    icp = "赣ICP备2022001242号-1"
    license = ""
    [params.footer.powered]
      enable = true
      hugoLogo = true
      themeLogo = true
    [params.footer.siteTime]
      enable = true
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = "已存活"
      value = "2022-01-19T13:49:00+08:00"
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0
  [params.archives]
    paginate = 25
    dateFormat = "01-02"
  [params.section]
    paginate = 20
    dateFormat = "01-02"
    [params.section.feed]
      limit = -1
      fullText = false
  [params.list]
    paginate = 20
    dateFormat = "01-02"
    [params.list.feed]
      limit = -1
      fullText = false
  [params.recentlyUpdated]
    archives = true
    section = true
    list = true
    days = 30
    maxCount = 10
  [params.home]
    paginate = 10
    [params.home.profile]
      enable = true
      gravatarEmail = "763771418@qq.com"
      avatarURL = "https://q.qlogo.cn/headimg_dl?dst_uin=763771418&spec=640"
      avatarMenu = ""
      title = "公爵书房"
      subtitle = "以指键之轻，承载知识之重"
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6
  [params.social]
    Mastodon = "@gjcloak"
    Github = "gongjuecloak"
    QQ = "763771418"
    Email = "763771418@qq.com"
    bilibili = "3054324"
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
    so = ""
    sogou = ""
  [params.analytics]
    enable = true
    [params.analytics.baidu]
      id = "4f7a563c757c9423f8b1208f9b00c480"
  [params.cookieconsent]
    enable = true
    [params.cookieconsent.content]
      message = "本站使用 Cookies 来改善您的浏览体验。"
      dismiss = "同意使用"
      link = "了解更多"
  [params.githubCorner]
    enable = true
    permalink = "https://github.com/gongjuecloak/hugo-my-Fixlt"
    title = "查看源码"
    position = "left"
  [params.backToTop]
    enable = true
    scrollpercent = false
  [params.readingProgress]
    enable = true
    start = "left"
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"
  [params.page]
    collectionList = true
    linkToSource = false
    linkToMarkdown = false
    linkToEdit = false
    linkToVscode = false
    linkToReport = true
    [params.page.expirationReminder]
      enable = true
      # 如果文章最后更新于这天数之前，显示提醒
      reminder = 90
      # 如果文章最后更新于这天数之前，显示警告
      warning = 180
      # 如果文章到期是否关闭评论
      closeComment = false
    # FixIt 0.3.0 | 新增 相关内容配置 (https://gohugo.io/content-management/related/)
    [params.page.related]
      enable = true
      count = 5
      position = ["aside"]
    # FixIt 0.2.17 | 新增 赞赏设置
    [params.page.reward]
      enable = false
      animation = false
      # 相对于页脚的位置，可选值：["before", "after"]
      position = "after"
      # comment = "Buy me a coffee"
      # FixIt 0.2.18 | 新增 二维码图片展示模式，可选值：["static", "fixed"]，默认：`static`
      mode = "static"
      [params.page.reward.ways]
        # wechatpay = "/images/wechatpay.png"
        # alipay = "/images/alipay.png"
        # paypal = "/images/paypal.png"
        # bitcoin = "/images/bitcoin.png"
    # 文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Myspace = false
      Blogger = false
      Baidu = true
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false
    # FixIt 0.2.15 | 更改 评论系统设置
    [params.page.comment]
      enable = true
      [params.page.comment.giscus]
        enable = true
        repo = "gongjuecloak/hugo-my-Fixlt"
        repoId = "R_kgDOPwo6Fg"
        category = "Announcements"
        categoryId = "DIC_kwDOPwo6Fs4Cvfbr"
        mapping = "pathname"
        origin = "https://giscus.app" # FixIt 0.3.7 | 新增 Or set it to your self-hosted domain
        strict = "0" # FixIt 0.2.18 | 新增
        term = ""
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom" # ["top", "bottom"]
        lightTheme = "light"
        darkTheme = "dark"
        lazyLoad = true
  [params.search]
    enable = true
    type = "fuse"
    contentLength = 4000
    placeholder = "输入你心中所想，我帮你把世界翻个遍！"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"

[menu]
  [[menu.main]]
    identifier = "home"
    parent = ""
    pre = ""
    post = ""
    name = "首页"
    url = "/"
    title = ""
    weight = 1
    [menu.main.params]
      icon = "fa-solid fa-home"
  [[menu.main]]
    identifier = "archives"
    parent = ""
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "文章"
    url = "/archives/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
    # FixIt 0.2.14 | NEW add user-defined content to menu items
    [menu.main.params]
      # add css class to a specific menu item
      class = ""
      # whether set as a draft menu item whose function is similar to a draft post/page
      draft = false
      # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
      icon = "fa-solid fa-archive"
      # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
      type = ""
      # FixIt 0.3.9 | NEW whether to show the submenu item divider line
      divided = false
  [[menu.main]]
    identifier = "collections"
    parent = "archives"
    pre = ""
    post = ""
    name = "合集"
    url = "/collections/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-layer-group"
  [[menu.main]]
    identifier = "categories"
    parent = "archives"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 4
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
  [[menu.main]]
    identifier = "tags"
    parent = "archives"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 5
    [menu.main.params]
      icon = "fa-solid fa-tags"
  [[menu.main]]
    identifier = "friends"
    parent = ""
    pre = ""
    post = ""
    name = "友链"
    url = "/friends/"
    title = ""
    weight = 6
    [menu.main.params]
      icon = "fa-solid fa-link"